spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.42.233.108:3306/ocdb?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Ahmckj.2017
  session:
    store-type: none
security:
  basic:
    enabled: true
server:
  port: 8080
#uizhi:
#  security:
#      browser:
#         loginPage: /demo-signIn.html

uizhi:
  security:
      browser:
         loginType: REDIRECT